apiVersion: v1
kind: Service
metadata:
  name: hello-php
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-php
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-php
  template:
    metadata:
      labels:
        app: hello-php
    spec:
      containers:
      - name: hello-php
        image: php-hello-world
        ports:
        - containerPort: 8080